version: "3"

services:
  # stable-diffusion-discord-bot
  arty:
    build: .
    container_name: arty
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    volumes:
      - ./config:/app/config # configuration file and database folder that must persist
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow refering to host gateway to access rembg (more reliable then hostname?)